genai_api_key = "AIzaSyCBpgo3aO4hYBbGjG2ULR0eZ2kY2G740wU"
cookies_password = "cookies_5430997924_py.secure-x-123"

[database]
username = "2Q8jvwVEw3JhUQc.root"
password = "3iCmIOx4j0NGJTQy"
host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"